# Generated by Django 4.2.7 on 2023-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='algorithm',
            field=models.CharField(db_column='algorithm', default=1, max_length=500),
            preserve_default=False,
        ),
    ]
